### ISSUE TITLE
AttributeError: 'Configurable' object has no attribute '_action_groups'

### ISSUE THREAD

**Issue by sfermigier** [morepath/more.pathtool#2]
Full stack trace:

```
$ morepathtool toto
Traceback (most recent call last):
  File "/Users/fermigier/envs/xsl/bin/morepathtool", line 11, in <module>
    load_entry_point('xsl-server', 'console_scripts', 'morepathtool')()
  File "/Users/fermigier/projects/eit-digital/xsl-server/xsl/web/main.py", line 15, in dump_path
    path_tool(App)
  File "/Users/fermigier/envs/xsl/lib/python2.7/site-packages/more/pathtool/main.py", line 35, in path_tool
    infos = get_path_and_view_info(app_class)
  File "/Users/fermigier/envs/xsl/lib/python2.7/site-packages/more/pathtool/main.py", line 106, in get_path_and_view_info
    for action, path in get_path_and_view_actions(app_class):
  File "/Users/fermigier/envs/xsl/lib/python2.7/site-packages/more/pathtool/main.py", line 161, in get_path_and_view_actions
    for action, f in q(app_class):
  File "/Users/fermigier/envs/xsl/lib/python2.7/site-packages/dectate/query.py", line 109, in query_action_classes
    action_group = configurable.get_action_group(action_class)
  File "/Users/fermigier/envs/xsl/lib/python2.7/site-packages/dectate/config.py", line 194, in get_action_group
    return self._action_groups.get(action_class, None)
AttributeError: 'Configurable' object has no attribute '_action_groups'
```

deps:

```
$ pip freeze
attrs==16.2.0
beautifulsoup4==4.5.1
cffi==1.8.3
cryptography==1.5.2
dectate==0.12
enum34==1.1.6
idna==2.1
importscan==0.1
ipaddress==1.0.17
more.jwtauth==0.8
more.pathtool==0.5
morepath==0.16.2
py==1.4.31
pyasn1==0.1.9
pycparser==2.17
PyJWT==1.4.2
pytest==3.0.3
reg==0.10
repoze.lru==0.6
six==1.10.0
waitress==1.0.1
WebOb==1.6.2
WebTest==2.0.23
xsl-server==0.0.0
```

**Comment by sfermigier** [comment]
Works after I added an `App.commit()`.
